name: Keep Backend Alive

on:
  schedule:
    - cron: "*/14 * * * *" # Runs every 14 minutes
  workflow_dispatch: # Optional: Allows manual triggering from GitHub

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: main # Explicitly checks out the main branch

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Use Node.js version 16

    - name: Run keep-alive script
      run: |
        npm install cron
        pwd
        node ./.github/workflows/cron.js